version: 2.1

parameters:
  project-root:
    type: string
    default: "~/home/dev/app-project"
  project-subdir-build:
    type: string
    default: "sdk-ameba-v4.0d_gcc/project/realtek_ameba1_va0_example/GCC-RELEASE"
  project-subdir-bin:
    type: string
    default: "sdk-ameba-v4.0d_gcc/project/realtek_ameba1_va0_example/GCC-RELEASE/application/Debug/bin"
  artifact-out:
    type: string
    default: "~/home/dev/out"
  gen-flash-home:
    type: string
    default: "/c/Users/circleci"
  gen-flash-repo:
    type: string
    default: "https://github.com/dexatek-mike/ci-win.git"
  config-support-mp-tool:
    type: boolean
    default: false
  config-native-build:
    type: boolean
    default: true
  config-fake-build:
    type: boolean
    default: false

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
      - image: yalee104/dk-ameba1:1.1
    environment:
      PATH_PROJECT_ROOT: << pipeline.parameters.project-root >>
      DIR_BUILD: << pipeline.parameters.project-subdir-build >>
      DIR_BIN: << pipeline.parameters.project-subdir-bin >>
      DIR_RELEASE: sdk-ameba-v4.0d_gcc/release
    parameters:
      out-dir:
        type: string
        default: normal
      build-mp-tool:
        type: boolean
        default: false
      release-build:
        type: boolean
        default: false
    working_directory: << pipeline.parameters.project-root >>
    steps:
      - when:
          condition: << pipeline.parameters.config-fake-build >>
          steps:
            - run: echo 'export FAKE_BUILD=y' >> $BASH_ENV
      - when:
          condition: << pipeline.parameters.config-native-build >>
          steps:
            - run: echo 'export NATIVE_BUILD=y' >> $BASH_ENV
      - when:
          condition: << parameters.release-build >>
          steps:
            - run: echo 'export RELEASE_BUILD=y' >> $BASH_ENV
      - when:
          condition: << parameters.build-mp-tool >>
          steps:
            - run:
                name: does not support building MP tool
                command: circleci-agent step halt
                unless: << pipeline.parameters.config-support-mp-tool >>
            - run: echo 'export BUILD_MP_TOOL=y' >> $BASH_ENV
      - checkout
      - run:
          name: Make (build project)
          command: |
            out_dir=<< parameters.out-dir >>

            pushd ${DIR_BUILD}
            # make; generate fake files to speed up tests if FAKE_BUILD is defined
            if [ "${FAKE_BUILD}" == 'y' ] ; then
              echo "fake build" > build.log
              mkdir -p ${DIR_BIN}
              echo "fake build" > ${DIR_BIN}/ota.bin
              echo "fake build" > ${DIR_BIN}/ram_all.bin
            else
              make > build.log 2>&1
            fi
            popd

            mkdir ${out_dir}
            cp ${DIR_BUILD}/build.log .
            cp ${DIR_BUILD}/build.log ${out_dir}/
            cp ${DIR_RELEASE}/* -r ${out_dir}/
            find ${DIR_RELEASE} -name "A000.dat" | xargs -i cp {} ${out_dir}
            cp ${DIR_BIN}/* -r ${out_dir}/
      - store_artifacts:
          path: << pipeline.parameters.project-root >>/build.log
          destination: << pipeline.parameters.artifact-out >>/build.log
          when: on_fail
      - run:
          name: build failed
          command: circleci-agent step halt
          when: on_fail
      - persist_to_workspace:
          root: << pipeline.parameters.project-root >>
          paths:
            - << parameters.out-dir >>
      - store_artifacts:
          path: << pipeline.parameters.project-root >>/<< parameters.out-dir >>/
          destination: << pipeline.parameters.artifact-out >>/bin
  gen_flash_bin:
    executor:
      name: win/vs2019
      shell: bash.exe
    environment:
      PATH_HOME: << pipeline.parameters.gen-flash-home >>
      PATH_PROJECT_REPO: << pipeline.parameters.gen-flash-repo >>
    working_directory: ~
    steps:
      - unless:
          condition: << pipeline.parameters.config-support-mp-tool >>
          steps:
            - run: echo 'NO_MP_OTA=y' >> $BASH_ENV
      - attach_workspace:
          at: ~/temp
      - run:
          name: generate flah.bin
          working_directory: ~
          command: |
            repo_dir="gen_flash"
            share_dir=~/temp

            cd ${PATH_HOME}
            git clone ${PATH_PROJECT_REPO} ${repo_dir}
            cd ${repo_dir}
            mkdir -p flash_bin/normal flash_bin/release

            cp ${share_dir}/normal/* ./ -r
            if [[ "${NO_MP_OTA}" == 'y' ]] ; then
              echo "no mp-tool image; use ota.bin"
              cp ota.bin mp_ota.bin
            else
              cp ${share_dir}/mp_tool/ota.bin mp_ota.bin
            fi
            sh gen_flash_bin.sh
            cp flash.bin flash_bin/normal/

            cp ${share_dir}/release/* ./ -r
            if [[ "${NO_MP_OTA}" == 'y' ]] ; then
              cp ota.bin mp_ota.bin
            else
              echo "no mp-tool image; use ota.bin"
              cp ${share_dir}/mp_tool/ota.bin mp_ota.bin
            fi
            sh gen_flash_bin.sh
            cp flash.bin flash_bin/release/
      - run:
          name: failed to generate flash image
          command: circleci-agent step halt
          when: on_fail
      - persist_to_workspace:
          root: C:\Users\circleci\gen_flash
          paths:
            - flash_bin
      - store_artifacts:
          path: C:\Users\circleci\gen_flash\flash_bin
          destination: << pipeline.parameters.artifact-out >>/flash_bin
workflows:
  version: 2.1
  build_and_pack:
    jobs:
      - build:
          name: build_normal
          out-dir: normal
          build-mp-tool: false
          release-build: false
      - build:
          name: build_release
          out-dir: release
          build-mp-tool: false
          release-build: true
      - build:
          name: build_mp_tool
          out-dir: mp_tool
          build-mp-tool: true
          release-build: true
      - gen_flash_bin:
          name: gen_flash
          requires:
            - build_normal
            - build_release
            - build_mp_tool
